/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef example_CONSTANTS_H
#define example_CONSTANTS_H

#include "example_types.h"

namespace example {

class exampleConstants {
 public:
  exampleConstants();

};

extern const exampleConstants g_example_constants;

} // namespace

#endif
